---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtrt
  labels:
    app: rtrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtrt
  template:
    metadata:
      labels:
        app: rtrt
    spec:
      containers:
        - name: rtrt
          image: docker.io/phengbunath/rtrt:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
